version: "3"

services:
    kali:
        container_name: kali_master
        hostname: kali_master
        image: lucagioacchini/kali-linux-headless:latest
        command: bash -c "
                    service ssh start &&
                    tail -f /dev/null"
        networks:
            net-192.168.100.0:
                ipv4_address: 192.168.100.5
        ports:
            - "20022:22"
        volumes:
            - /home/user:/opt

    access_control_vm0:
        build: ./machines/access_control/vm0
        image: access_control_vm0
        container_name: access_control_vm0
        hostname: access_control_vm0
        tty: true
        init: true
        networks:
            net-192.168.100.0:
                ipv4_address: 192.168.100.10
        command: bash -c "
                    service ssh start &&
                    tail -f /dev/null"
        restart: unless-stopped
        ports:
            - "2220:22"
        volumes:
            - ./machines/access_control/vm0/flag:/root/flag

    access_control_vm1:
        build: ./machines/access_control/vm1
        image: access_control_vm1
        container_name: access_control_vm1
        hostname: access_control_vm1
        tty: true
        init: true
        networks:
            net-192.168.100.0:
                ipv4_address: 192.168.100.11
        command: bash -c "
                    setfacl -m u:student:rwx /etc/shadow &&
                    service ssh start &&
                    tail -f /dev/null"
        restart: unless-stopped
        ports:
            - "2221:22"
        volumes:
            - ./machines/access_control/vm1/flag:/root/flag

    access_control_vm2:
        build: ./machines/access_control/vm2
        image: access_control_vm2
        container_name: access_control_vm2
        hostname: access_control_vm2
        tty: true
        init: true
        networks:
            net-192.168.100.0:
                ipv4_address: 192.168.100.12
        command: bash -c "
                    service ssh start &&
                    cron -f"
        restart: unless-stopped
        ports:
            - "2222:22"
        volumes:
            - ./machines/access_control/vm2/flag:/root/flag

    access_control_vm3:
        build: ./machines/access_control/vm3
        image: access_control_vm3
        container_name: access_control_vm3
        hostname: access_control_vm3
        tty: true
        init: true
        networks:
            net-192.168.100.0:
                ipv4_address: 192.168.100.13
        command: bash -c "
                    service ssh start &&
                    tail -f /dev/null"
        restart: unless-stopped
        ports:
            - "2223:22"
        volumes:
            - ./machines/access_control/vm3/flag:/root/flag

    access_control_vm4:
        build: ./machines/access_control/vm4
        image: access_control_vm4
        container_name: access_control_vm4
        hostname: access_control_vm4
        tty: true
        init: true
        networks:
            net-192.168.100.0:
                ipv4_address: 192.168.100.14
        command: bash -c "
                    service ssh start &&
                    tail -f /dev/null"
        restart: unless-stopped
        ports:
            - "2224:22"
        volumes:
            - ./machines/access_control/vm4/flag:/root/flag

    access_control_vm5:
        build: ./machines/access_control/vm5
        image: access_control_vm5
        container_name: access_control_vm5
        hostname: access_control_vm5
        tty: true
        init: true
        networks:
            net-192.168.100.0:
                ipv4_address: 192.168.100.15
        command: bash -c "
                    service ssh start &&
                    tail -f /dev/null"
        restart: unless-stopped
        ports:
            - "2225:22"
        volumes:
            - ./machines/access_control/vm5/flag:/root/flag

networks:
    net-192.168.100.0:
        name: net-192.168.100.0
        internal: false
        ipam:
            config:
                - subnet: 192.168.100.0/24
